# Week 6: Show off your pandas skills
What's the relationship between vaccination rates and post-vaccination deaths?

#### Load python tools:

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/datadesk/california-coronavirus-data/master/cdph-vaccination-county-totals.csv')

### Explore the dataset

In [3]:
df.head()

,date,county,fips,population,doses_administered,new_doses_administered,pfizer_doses,new_pfizer_doses,moderna_doses,new_moderna_doses,...,new_jj_doses,partially_vaccinated,new_partially_vaccinated,at_least_one_dose,new_at_least_one_dose,fully_vaccinated,new_fully_vaccinated,partially_vaccinated_percent,at_least_one_dose_percent,fully_vaccinated_percent
0,2022-02-21,Alameda,1,1643700.0,3504668,493,2138982.0,299,1065487.0,143,...,13,107066.0,93,1450742.0,98,1343676.0,108,0.065137,0.882608,0.817470
1,2022-02-21,Alpine,3,1148.0,1865,0,73.0,0,1769.0,0,...,0,139.0,0,857.0,0,718.0,0,0.121080,0.746516,0.625436
2,2022-02-21,Amador,5,37829.0,54202,7,15852.0,3,35882.0,4,...,0,3890.0,1,24511.0,1,20621.0,0,0.102831,0.647942,0.545111
3,2022-02-21,Butte,7,227075.0,288365,30,141977.0,15,130419.0,13,...,0,10626.0,3,125162.0,3,114536.0,8,0.046795,0.551192,0.504397
4,2022-02-21,Calaveras,9,45235.0,63249,4,26952.0,0,33965.0,4,...,0,4392.0,1,28541.0,1,24149.0,1,0.097093,0.630949,0.533857

#### Numbers of rows in data

In [4]:
len(df)

45182

#### Sort by fully vaccinated individuals

In [5]:
df.sort_values('county', ascending=False).head()

,date,county,fips,population,doses_administered,new_doses_administered,pfizer_doses,new_pfizer_doses,moderna_doses,new_moderna_doses,...,new_jj_doses,partially_vaccinated,new_partially_vaccinated,at_least_one_dose,new_at_least_one_dose,fully_vaccinated,new_fully_vaccinated,partially_vaccinated_percent,at_least_one_dose_percent,fully_vaccinated_percent
45181,2020-01-05,Yuba,115,75493.0,0,0,0.0,0,0.0,0,...,0,0.0,0,0.0,0,0.0,0,0.000000,0.000000,0.000000
27085,2020-11-12,Yuba,115,75493.0,2,0,0.0,0,2.0,0,...,0,0.0,0,1.0,0,1.0,0,0.000000,0.000013,0.000013
17225,2021-05-01,Yuba,115,75493.0,36145,226,11244.0,99,22609.0,106,...,21,5453.0,102,21894.0,123,16441.0,123,0.072232,0.290014,0.217782
27317,2020-11-08,Yuba,115,75493.0,2,0,0.0,0,2.0,0,...,0,0.0,0,1.0,0,1.0,0,0.000000,0.000013,0.000013
39787,2020-04-07,Yuba,115,75493.0,0,0,0.0,0,0.0,0,...,0,0.0,0,0.0,0,0.0,0,0.000000,0.000000,0.000000

#### How many individuals are fully vaccinated?

In [6]:
df.value_counts('fully_vaccinated')

fully_vaccinated
0.0          15803
1.0           1476
2.0            678
3.0            315
5.0            315
             ...
38083.0          1
38067.0          1
38049.0          1
38048.0          1
7225579.0        1
Length: 21432, dtype: int64

#### Explore distributions

In [10]:
df.describe(exclude=None)

,fips,population,doses_administered,new_doses_administered,pfizer_doses,new_pfizer_doses,moderna_doses,new_moderna_doses,jj_doses,new_jj_doses,partially_vaccinated,new_partially_vaccinated,at_least_one_dose,new_at_least_one_dose,fully_vaccinated,new_fully_vaccinated,partially_vaccinated_percent,at_least_one_dose_percent,fully_vaccinated_percent
count,45182.000000,4.518200e+04,4.518200e+04,45182.000000,4.518200e+04,45182.000000,4.518200e+04,45182.000000,45182.000000,45182.000000,4.518200e+04,45182.000000,4.518200e+04,45182.000000,4.518200e+04,45182.000000,45182.000000,45182.000000,45182.000000
mean,58.000000,6.749787e+05,3.715605e+05,1551.621619,2.090199e+05,871.709730,1.462932e+05,578.497366,12592.363242,48.826059,2.792896e+04,627.503940,1.930299e+05,677.390930,1.651010e+05,610.437254,0.039456,0.259310,0.219854
std,33.481709,1.456937e+06,1.325799e+06,6044.001580,7.429149e+05,3259.152443,5.223466e+05,2531.253174,47825.598129,393.308495,9.551247e+04,2801.117965,6.704323e+05,3046.567122,5.912492e+05,2823.978104,0.045043,0.293660,0.263648
min,1.000000,1.148000e+03,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000
25%,29.000000,4.523500e+04,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000
50%,58.000000,1.834385e+05,4.359000e+03,15.000000,1.204500e+03,5.000000,2.452000e+03,5.000000,3.000000,0.000000,7.870000e+02,5.000000,3.149000e+03,6.000000,8.645000e+02,2.000000,0.030661,0.068317,0.014088
75%,87.000000,7.322120e+05,1.599985e+05,640.000000,8.014400e+04,343.000000,7.273375e+04,210.000000,5063.500000,9.000000,1.514875e+04,219.750000,8.999850e+04,238.000000,6.646725e+04,186.000000,0.066447,0.537667,0.465902
max,115.000000,1.009805e+07,1.837491e+07,139634.000000,1.009009e+07,71707.000000,7.102202e+06,63073.000000,614929.000000,25336.000000,1.524262e+06,74223.000000,8.015918e+06,89084.000000,7.225579e+06,78600.000000,0.320160,1.208727,0.888567

#### Most recent

In [13]:
latest_df = df[df["date"] == df["date"].max()]

In [14]:
len(latest_df)

58

#### Columns

In [15]:
essential_df = latest_df[["county", "fully_vaccinated_percent", "population"]]

In [17]:
essential_df.head()

      county  fully_vaccinated_percent  population
0    Alameda                  0.817470   1643700.0
1     Alpine                  0.625436      1148.0
2     Amador                  0.545111     37829.0
3      Butte                  0.504397    227075.0
4  Calaveras                  0.533857     45235.0

### Post-vaccination deaths

In [22]:
post_df = pd.read_csv('https://raw.githubusercontent.com/stiles/usc/main/data/raw/post_vacc.csv')

In [23]:
post_df.head()

,date,area,area_type,unvaccinated_cases,vaccinated_cases,boosted_cases,unvaccinated_hosp,vaccinated_hosp,boosted_hosp,unvaccinated_deaths,...,population_boosted,unvaccinated_cases_per_100k,vaccinated_cases_per_100k,boosted_cases_per_100k,unvaccinated_hosp_per_100k,vaccinated_hosp_per_100k,boosted_hosp_per_100k,unvaccinated_deaths_per_100k,vaccinated_deaths_per_100k,boosted_deaths_per_100k
0,2021-02-01,California,State,13848,22,0,761,0,0,12,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-02-02,California,State,11380,17,0,590,0,0,15,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021-02-03,California,State,10355,26,0,545,0,0,17,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021-02-04,California,State,9022,17,0,478,0,0,19,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021-02-05,California,State,8416,17,0,488,0,0,27,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN