# Data from HTML tables: U.S. births

In [10]:
%load_ext lab_black
import pandas as pd
import altair as alt

#### Get url

In [11]:
url = "https://www.ssa.gov/oact/babynames/numberUSbirths.html"

#### Read it into a dataframe

In [12]:
births = pd.read_html(url)[0]
births

     Year of birth     Male   Female    Total
0             1880   118399    97606   216005
1             1881   108280    98855   207135
2             1882   122031   115694   237725
3             1883   112475   120059   232534
4             1884   122738   137585   260323
..             ...      ...      ...      ...
136           2016  2022858  1933195  3956053
137           2017  1975558  1885970  3861528
138           2018  1939284  1855454  3794738
139           2019  1914661  1828242  3742903
140           2020  1831432  1751046  3582478

[141 rows x 4 columns]

#### Clean up columns

In [15]:
births.rename(
    columns={
        "Year of birth": "year",
        "Male": "male",
        "Female": "female",
        "Total": "total",
    },
    inplace=True,
)

In [16]:
births.head()

   year    male  female   total
0  1880  118399   97606  216005
1  1881  108280   98855  207135
2  1882  122031  115694  237725
3  1883  112475  120059  232534
4  1884  122738  137585  260323

#### Convert year

In [18]:
births.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 141 entries, 0 to 140
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   year    141 non-null    int64
 1   male    141 non-null    int64
 2   female  141 non-null    int64
 3   total   141 non-null    int64
dtypes: int64(4)
memory usage: 4.5 KB

In [21]:
births["year"] = births["year"].astype(str)
births.dtypes

year      object
male       int64
female     int64
total      int64
dtype: object

#### Chart it!

In [25]:
alt.Chart(births).mark_bar(color="orange").encode(x="year:T", y="total").properties(
    width=650
)

alt.Chart(...)

In [3]:
# births.to_csv('../../data/processed/ssa_births_1880_2020.csv', index=False)

---

## Get data from Wikipedia

In [51]:
# Used in this story:
url2 = "https://en.wikipedia.org/wiki/United_States_midterm_election"
# "https://www.grid.news/story/politics/2022/01/13/what-economic-and-political-indicators-tell-us-about-the-2022-midterms/"

In [52]:
wiki_df = pd.read_html(url2, header=0)[1]
wiki_df.drop([0], inplace=True)

In [59]:
wiki_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 58 entries, 1 to 58
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   year             58 non-null     object
 1   president        58 non-null     object
 2   president_party  58 non-null     object
 3   house_loss       58 non-null     object
 4   senate_loss      58 non-null     object
dtypes: object(5)
memory usage: 2.7+ KB

#### Clean up the column names

#### Make them lower case

In [62]:
wiki_df.columns = (
    wiki_df.columns.str.lower()
    .str.replace(" ", "_", regex=False)
    .str.replace("/", "_", regex=False)
)
wiki_df

,year,president,president_party,house_loss,senate_loss
1,1790,George Washington,None[a],+3: (37 â–º 40),0: (18 â–º 18)
2,1794,George Washington,None[a],-4: (51 â–º 47),+3: (16 â–º 19)
3,1798,John Adams,Federalist,+3: (57 â–º 60),0: (22 â–º 22)
4,1802,Thomas Jefferson,Democratic-Republican,+1: (38 â–º 39),-6: (15 â–º 9)
5,1806,Thomas Jefferson,Democratic-Republican,+2: (114 â–º 116),+1: (27 â–º 28)
6,1810,James Madison,Democratic-Republican,+13: (94 â–º 107),0: (26 â–º 26)
7,1814,James Madison,Democratic-Republican,+5: (114 â–º 119),-3: (26 â–º 22)
8,1818,James Monroe,Democratic-Republican,+13: (145 â–º 158),+2: (28 â–º 30)
9,1822,James Monroe,Democratic-Republican,+34: (155 â–º 189),0: (44 â–º 44)
10,1826,John Quincy Adams,Democratic-Republican[b],-9: (109 â–º 100),-2: (21 â–º 19)
11,1830,Andrew Jackson,Democratic[c],-10: (136 â–º 126),+1: (25 â–º 26)
12,1834,Andrew Jackson,Democratic[c],0: (143 â–º 143),+1: (21 â–º 22)
13,1838,Martin Van Buren,Democratic,-3: (128 â–º 125),-7: (35 â–º 28)
14,1842,John Tyler,None[d],-69: (142 â–º 73),-3: (30 â–º 27)
15,1846,James K. Polk,Democratic,-30: (142 â–º 112),+2: (33 â–º 35)
16,1850,Millard Fillmore,Whig,-22: (108 â–º 86),-3: (36 â–º 33)
17,1854,Franklin Pierce,Democratic,-75: (158 â–º 83),-3: (36 â–º 33)
18,1858,James Buchanan,Democratic,-35: (133 â–º 98),-4: (32 â–º 38)
19,1862,Abraham Lincoln,Republican,-23: (108 â–º 85),+1: (31 â–º 32)
20,1866,Andrew Johnson,National Union[e],+9: (38 â–º 47),0: (10 â–º 10)
21,1870,Ulysses S. Grant,Republican,-32: (171 â–º 139),-5: (63 â–º 58)
22,1874,Ulysses S. Grant,Republican,-93: (199 â–º 106),-10: (52 â–º 42)
23,1878,Rutherford B. Hayes,Republican,-4: (136 â–º 132),-7: (38 â–º 31)
24,1882,Chester A. Arthur,Republican,-29: (151 â–º 118),0: (37 â–º 37)
25,1886,Grover Cleveland,Democratic,-16: (183 â–º 167),+2: (34 â–º 36)
26,1890,Benjamin Harrison,Republican,-93: (179 â–º 86),-4: (47 â–º 43)
27,1894,Grover Cleveland,Democratic,-127: (220 â–º 93),-4: (44 â–º 40)
28,1898,William McKinley,Republican,-21: (205 â–º 189),+6: (44 â–º 50)
29,1902,Theodore Roosevelt,Republican,+9: (201 â–º 210),0: (55 â–º 55)
30,1906,Theodore Roosevelt,Republican,-27: (251 â–º 224),+2: (58 â–º 60)
31,1910,William Howard Taft,Republican,-56: (219 â–º 163),-9: (59 â–º 50)
32,1914,Woodrow Wilson,Democratic,-61: (291 â–º 230),+3: (50 â–º 53)
33,1918,Woodrow Wilson,Democratic,-22: (214 â–º 192),-4: (52 â–º 48)
34,1922,Warren G. Harding,Republican,-77: (302 â–º 225),-7: (60 â–º 53)
35,1926,Calvin Coolidge,Republican,-9: (247 â–º 238),-6: (56 â–º 50)
36,1930,Herbert Hoover,Republican,-52: (270 â–º 218),-6: (56 â–º 50)
37,1934,Franklin D. Roosevelt,Democratic,+9: (313 â–º 322),+9: (60 â–º 69)
38,1938,Franklin D. Roosevelt,Democratic,-72: (334 â–º 262),-7: (75 â–º 68)
39,1942,Franklin D. Roosevelt,Democratic,-45: (267 â–º 222),-8: (65 â–º 57)
40,1946,Harry S. Truman,Democratic,-54: (242 â–º 188),-10: (56 â–º 46)
41,1950,Harry S. Truman,Democratic,-28: (263 â–º 235),-5: (54 â–º 49)
42,1954,Dwight D. Eisenhower,Republican,-18: (221 â–º 203),-2: (49 â–º 47)
43,1958,Dwight D. Eisenhower,Republican,-48: (201 â–º 153),-12: (47 â–º 35)
44,1962,John F. Kennedy,Democratic,-4: (262 â–º 258),+4: (64 â–º 68)
45,1966,Lyndon B. Johnson,Democratic,-47: (295 â–º 248),-3: (67 â–º 64)
46,1970,Richard Nixon,Republican,-12: (192 â–º 180),+2: (43 â–º 45)
47,1974,Gerald Ford,Republican,-48: (192 â–º 144),-4: (42 â–º 38)
48,1978,Jimmy Carter,Democratic,-15: (292 â–º 277),-2: (61 â–º 59)
49,1982,Ronald Reagan,Republican,-26: (192 â–º 166),0: (54 â–º 54)
50,1986,Ronald Reagan,Republican,-5: (182 â–º 177),-8: (53 â–º 45)
51,1990,George H. W. Bush,Republican,-8: (175 â–º 167),-1: (45 â–º 44)
52,1994,Bill Clinton,Democratic,-54: (258 â–º 204),-10: (57 â–º 47)
53,1998,Bill Clinton,Democratic,+4: (207 â–º 211),0: (45 â–º 45)
54,2002,George W. Bush,Republican,+8: (221 â–º 229),+2: (49 â–º 51)
55,2006,George W. Bush,Republican,-32: (231 â–º 199),-6: (55 â–º 49)
56,2010,Barack Obama,Democratic,-63: (256 â–º 193),-6: (57 â–º 51)
57,2014,Barack Obama,Democratic,-13: (201 â–º 188),-9: (53 â–º 44)
58,2018,Donald Trump,Republican,-40: (240 â–º 200)[f],+2: (51 â–º 53)

#### Or just rename them entirely

In [57]:
wiki_df.columns = ["year", "president", "president_party", "house_loss", "senate_loss"]
wiki_df.head()

,year,president,president_party,house_loss,senate_loss
1,1790,George Washington,None[a],+3: (37 â–º 40),0: (18 â–º 18)
2,1794,George Washington,None[a],-4: (51 â–º 47),+3: (16 â–º 19)
3,1798,John Adams,Federalist,+3: (57 â–º 60),0: (22 â–º 22)
4,1802,Thomas Jefferson,Democratic-Republican,+1: (38 â–º 39),-6: (15 â–º 9)
5,1806,Thomas Jefferson,Democratic-Republican,+2: (114 â–º 116),+1: (27 â–º 28)

#### First five rows

In [58]:
wiki_df.head()

,year,president,president_party,house_loss,senate_loss
1,1790,George Washington,None[a],+3: (37 â–º 40),0: (18 â–º 18)
2,1794,George Washington,None[a],-4: (51 â–º 47),+3: (16 â–º 19)
3,1798,John Adams,Federalist,+3: (57 â–º 60),0: (22 â–º 22)
4,1802,Thomas Jefferson,Democratic-Republican,+1: (38 â–º 39),-6: (15 â–º 9)
5,1806,Thomas Jefferson,Democratic-Republican,+2: (114 â–º 116),+1: (27 â–º 28)

#### Filter to presidents after 1900

In [ ]:
#wiki_df[wiki_df['year']>1900]

#### First, convert data type on year column

In [60]:
wiki_df["year"] = wiki_df["year"].astype(int)

#### Now try the filter

In [61]:
wiki_df[wiki_df["year"] > 1900]

,year,president,president_party,house_loss,senate_loss
29,1902,Theodore Roosevelt,Republican,+9: (201 â–º 210),0: (55 â–º 55)
30,1906,Theodore Roosevelt,Republican,-27: (251 â–º 224),+2: (58 â–º 60)
31,1910,William Howard Taft,Republican,-56: (219 â–º 163),-9: (59 â–º 50)
32,1914,Woodrow Wilson,Democratic,-61: (291 â–º 230),+3: (50 â–º 53)
33,1918,Woodrow Wilson,Democratic,-22: (214 â–º 192),-4: (52 â–º 48)
34,1922,Warren G. Harding,Republican,-77: (302 â–º 225),-7: (60 â–º 53)
35,1926,Calvin Coolidge,Republican,-9: (247 â–º 238),-6: (56 â–º 50)
36,1930,Herbert Hoover,Republican,-52: (270 â–º 218),-6: (56 â–º 50)
37,1934,Franklin D. Roosevelt,Democratic,+9: (313 â–º 322),+9: (60 â–º 69)
38,1938,Franklin D. Roosevelt,Democratic,-72: (334 â–º 262),-7: (75 â–º 68)
39,1942,Franklin D. Roosevelt,Democratic,-45: (267 â–º 222),-8: (65 â–º 57)
40,1946,Harry S. Truman,Democratic,-54: (242 â–º 188),-10: (56 â–º 46)
41,1950,Harry S. Truman,Democratic,-28: (263 â–º 235),-5: (54 â–º 49)
42,1954,Dwight D. Eisenhower,Republican,-18: (221 â–º 203),-2: (49 â–º 47)
43,1958,Dwight D. Eisenhower,Republican,-48: (201 â–º 153),-12: (47 â–º 35)
44,1962,John F. Kennedy,Democratic,-4: (262 â–º 258),+4: (64 â–º 68)
45,1966,Lyndon B. Johnson,Democratic,-47: (295 â–º 248),-3: (67 â–º 64)
46,1970,Richard Nixon,Republican,-12: (192 â–º 180),+2: (43 â–º 45)
47,1974,Gerald Ford,Republican,-48: (192 â–º 144),-4: (42 â–º 38)
48,1978,Jimmy Carter,Democratic,-15: (292 â–º 277),-2: (61 â–º 59)
49,1982,Ronald Reagan,Republican,-26: (192 â–º 166),0: (54 â–º 54)
50,1986,Ronald Reagan,Republican,-5: (182 â–º 177),-8: (53 â–º 45)
51,1990,George H. W. Bush,Republican,-8: (175 â–º 167),-1: (45 â–º 44)
52,1994,Bill Clinton,Democratic,-54: (258 â–º 204),-10: (57 â–º 47)
53,1998,Bill Clinton,Democratic,+4: (207 â–º 211),0: (45 â–º 45)
54,2002,George W. Bush,Republican,+8: (221 â–º 229),+2: (49 â–º 51)
55,2006,George W. Bush,Republican,-32: (231 â–º 199),-6: (55 â–º 49)
56,2010,Barack Obama,Democratic,-63: (256 â–º 193),-6: (57 â–º 51)
57,2014,Barack Obama,Democratic,-13: (201 â–º 188),-9: (53 â–º 44)
58,2018,Donald Trump,Republican,-40: (240 â–º 200)[f],+2: (51 â–º 53)

#### Export

In [63]:
wiki_df.to_csv("../data/processed/wiki_midterm_gains_losses_party.csv", index=False)