# Class mapping exercise
Choose one of the map ideas below, processed the data with GeoPandas and export the data to QGIS for presentation. *Hint: You might need to change data types using the `dtype` argument when importing files so that you can merge with FIPS and ZIP codes effectively.*

#### Load python tools

In [1]:
%load_ext lab_black

In [2]:
import pandas as pd
import geopandas as gpd
import numpy as np

In [3]:
pd.options.display.max_columns = 1000
pd.options.display.max_rows = 1000

### Election map
#### What percentage of vote did Biden/Trump receive in California counties?

In [4]:
# Values: https://raw.githubusercontent.com/stiles/notebooks/master/elections/data/ca_counties_election_results_2020.csv
# Geo: https://raw.githubusercontent.com/stiles/usc/main/data/geo/counties_simple.geojson

#### Read election results

In [ ]:
###tesla_df = pd.read_csv(
###"https://raw.githubusercontent.com/stiles/notebooks/master/elections/data/ca_counties_election_results_2020.csv")

#### Read county boundaries

#### Merge the two

---

### Vehicle map
##### What's the Tesla ownership rate by LA ZIP Codes?

In [5]:
# Values: https://raw.githubusercontent.com/stiles/notebooks/master/california-fuel-vehicles/output/tesla_zips_slim.csv
# Geo: https://raw.githubusercontent.com/stiles/notebooks/master/zips/data/processed/ca_zips_simple.geojson.json

#### Read Tesla data

In [4]:
tesla_df = pd.read_csv(
    "https://raw.githubusercontent.com/stiles/notebooks/master/california-fuel-vehicles/output/tesla_zips_slim.csv"
{"zip"=str})

SyntaxError: invalid syntax (<ipython-input-4-f03b93d59491>, line 3)

ERROR:root:Cannot parse: 3:0: {"zip"=str})
Traceback (most recent call last):
  File "/Users/graceharmon/opt/anaconda3/lib/python3.8/site-packages/lab_black.py", line 218, in format_cell
    formatted_code = _format_code(cell)
  File "/Users/graceharmon/opt/anaconda3/lib/python3.8/site-packages/lab_black.py", line 29, in _format_code
    return format_str(src_contents=code, mode=FileMode())
  File "/Users/graceharmon/opt/anaconda3/lib/python3.8/site-packages/black.py", line 725, in format_str
    src_node = lib2to3_parse(src_contents.lstrip(), mode.target_versions)
  File "/Users/graceharmon/opt/anaconda3/lib/python3.8/site-packages/black.py", line 836, in lib2to3_parse
    raise exc from None
black.InvalidInput: Cannot parse: 3:0: {"zip"=str})

#### Read ZIP Codes geo file

#### Merge the two

#### Export merged geo file

---

### Population map
##### How's the white population distributed in LA by neighborhood?

In [6]:
# Values:https://raw.githubusercontent.com/stiles/usc/main/data/processed/la_neighborhood_demographics.csv
# Geo: https://raw.githubusercontent.com/stiles/usc/main/data/geo/la-neighborhoods.geojson

#### Read race/ethnicity data

In [6]:
whites_la_df = pd.read_csv(
    "https://raw.githubusercontent.com/stiles/usc/main/data/processed/la_neighborhood_demographics.csv"
)

In [7]:
whites_la_df.head()

,name,total_population,white_alone,black_alone,american_indian_and_alaska_native,asian_alone,native_hawaiian_and_pacific_islander,other_alone,two_or_more_races,latino_alone,asians_all,other_all,white_percent,black_percent,american_indian_percent,asian_percent,native_hawaiian_percent,other_percent,two_or_more_races_percent,latino_percent,asians_all_percent,other_all_percent,nonwhite_percent,majority_nonwhite,majority_white,majority_black,majority_american_indian_and_alaska_native,majority_asian,majority_native_hawaiian,majority_other,majority_two_or_more_races,majority_latino,median_householdincome,total_occupied_housing_units,owner_occupied,renter_occupied,owner_percent,renter_percent,majority_owner,majority_renter,majorityhigherthanmedianincomeLA
0,Acton,13533.0,3030.0,43.0,9.0,122.0,0.0,0.0,64.0,1019.0,123.0,73.0,22.39,0.32,0.07,0.90,0.00,0.00,0.47,7.53,0.91,0.54,77.61,True,False,False,False,False,False,False,False,False,99453.506605,1474.265218,1329.164851,145.100367,0.901578,0.098422,True,False,True
1,Adams-Normandie,37987.0,1455.0,3601.0,6.0,1622.0,62.0,32.0,273.0,11751.0,1683.0,311.0,3.83,9.48,0.02,4.27,0.16,0.08,0.72,30.93,4.43,0.82,96.17,True,False,False,False,False,False,False,False,False,37419.270130,5437.575802,1123.870291,4313.705512,0.206686,0.793314,False,True,False
2,Agoura Hills,27220.0,9337.0,415.0,0.0,1055.0,0.0,32.0,418.0,1548.0,1055.0,451.0,34.30,1.52,0.00,3.88,0.00,0.12,1.54,5.69,3.88,1.66,65.70,True,False,False,False,False,False,False,False,False,121211.788628,4675.116219,3311.101230,1364.014989,0.708239,0.291761,True,False,True
3,Agua Dulce,17982.0,3431.0,84.0,29.0,176.0,2.0,4.0,131.0,1025.0,179.0,164.0,19.08,0.47,0.16,0.98,0.01,0.02,0.73,5.70,0.99,0.91,80.92,True,False,False,False,False,False,False,False,False,108312.326136,1490.569409,1408.056410,82.512999,0.944643,0.055357,True,False,True
4,Alhambra,105896.0,3511.0,810.0,109.0,19403.0,191.0,149.0,773.0,15428.0,19594.0,1031.0,3.32,0.76,0.10,18.32,0.18,0.14,0.73,14.57,18.50,0.97,96.68,True,False,False,False,False,False,False,False,False,61884.537960,13840.151455,5937.368580,7902.782874,0.428996,0.571004,False,True,False

In [12]:
whites_la_df[whites_la_df["name"] == "Koreatown"]

,name,total_population,white_alone,black_alone,american_indian_and_alaska_native,asian_alone,native_hawaiian_and_pacific_islander,other_alone,two_or_more_races,latino_alone,asians_all,other_all,white_percent,black_percent,american_indian_percent,asian_percent,native_hawaiian_percent,other_percent,two_or_more_races_percent,latino_percent,asians_all_percent,other_all_percent,nonwhite_percent,majority_nonwhite,majority_white,majority_black,majority_american_indian_and_alaska_native,majority_asian,majority_native_hawaiian,majority_other,majority_two_or_more_races,majority_latino,median_householdincome,total_occupied_housing_units,owner_occupied,renter_occupied,owner_percent,renter_percent,majority_owner,majority_renter,majorityhigherthanmedianincomeLA
113,Koreatown,164051.0,10099.0,5623.0,363.0,39544.0,353.0,271.0,1905.0,47904.0,39898.0,2538.0,6.16,3.43,0.22,24.1,0.22,0.17,1.16,29.2,24.32,1.55,93.84,True,False,False,False,False,False,False,False,False,42886.988875,43536.405263,2948.28562,40588.119643,0.06772,0.93228,False,True,False

#### Read LA neighborhoods geo file

In [8]:
la_hoods_df = gpd.read_file(
    "https://raw.githubusercontent.com/stiles/usc/main/data/geo/la-neighborhoods.geojson"
)

In [9]:
la_hoods_df.head()

,name,slug,county,type,city,region,geometry
0,Vermont Square,vermont-square,los-angeles,Los Angeles,los-angeles,south-la,"POLYGON ((-118.28273 34.01114, -118.28207 34.0..."
1,Arlington Heights,arlington-heights,los-angeles,Los Angeles,los-angeles,central-la,"POLYGON ((-118.31672 34.05250, -118.31649 34.0..."
2,Bel-Air,bel-air,los-angeles,Los Angeles,los-angeles,westside,"POLYGON ((-118.46076 34.13033, -118.46068 34.1..."
3,Beverly Crest,beverly-crest,los-angeles,Los Angeles,los-angeles,westside,"POLYGON ((-118.45139 34.13176, -118.45116 34.1..."
4,Beverlywood,beverlywood,los-angeles,Los Angeles,los-angeles,westside,"POLYGON ((-118.39426 34.05244, -118.39317 34.0..."

#### Merge the two

In [14]:
la_hoods_race_gdf = pd.merge(whites_la_df, la_hoods_df, on="name")

#### Export merged geo file

In [ ]:
la_hoods_race_gdf.to_file("https://raw.githubusercontent.com/stiles/usc/main/data/geo/la-neighborhoods.geojson")