In [1]:
import pandas as pd

In [2]:
import geopandas as gpd
import numpy as np

In [3]:
%load_ext lab_black

In [4]:
import altair as alt

In [5]:
domestic_violence_df = pd.read_csv("domestic_violence.csv")

In [6]:
domestic_violence_df.columns = domestic_violence_df.columns.str.lower().str.replace(
    " ", "", regex=False
)

In [7]:
domestic_violence_df["rptdistno"] = domestic_violence_df["rptdistno"].astype(str)

In [8]:
domestic_violence_df.head()

,dr_no,daterptd,dateocc,timeocc,area,areaname,rptdistno,part1-2,crmcd,crmcddesc,...,status,statusdesc,crmcd1,crmcd2,crmcd3,crmcd4,location,crossstreet,lat,lon
0,200407198,03/22/2020 12:00:00 AM,03/22/2020 12:00:00 AM,430,4,Hollenbeck,466,2,626,INTIMATE PARTNER - SIMPLE ASSAULT,...,AO,Adult Other,626,NaN,NaN,NaN,300 N EVERGREEN AV,NaN,34.0436,-118.2051
1,200104033,01/01/2020 12:00:00 AM,01/01/2020 12:00:00 AM,230,1,Central,143,2,626,INTIMATE PARTNER - SIMPLE ASSAULT,...,IC,Invest Cont,626,NaN,NaN,NaN,400 S HILL ST,NaN,34.0503,-118.2504
2,200104101,01/02/2020 12:00:00 AM,01/02/2020 12:00:00 AM,800,1,Central,131,2,626,INTIMATE PARTNER - SIMPLE ASSAULT,...,IC,Invest Cont,626,NaN,NaN,NaN,100 S FIGUEROA ST,NaN,34.0569,-118.2540
3,200104140,01/02/2020 12:00:00 AM,01/02/2020 12:00:00 AM,2145,1,Central,192,2,626,INTIMATE PARTNER - SIMPLE ASSAULT,...,AA,Adult Arrest,626,NaN,NaN,NaN,1300 S HOPE ST,NaN,34.0395,-118.2656
4,200104325,01/06/2020 12:00:00 AM,01/06/2020 12:00:00 AM,30,1,Central,185,2,626,INTIMATE PARTNER - SIMPLE ASSAULT,...,AA,Adult Arrest,626,NaN,NaN,NaN,1000 S BROADWAY,NaN,34.0409,-118.2574

In [9]:
domestic_violence_df.tail()

,dr_no,daterptd,dateocc,timeocc,area,areaname,rptdistno,part1-2,crmcd,crmcddesc,...,status,statusdesc,crmcd1,crmcd2,crmcd3,crmcd4,location,crossstreet,lat,lon
39765,222104545,01/18/2022 12:00:00 AM,01/18/2022 12:00:00 AM,320,21,Topanga,2144,2,626,INTIMATE PARTNER - SIMPLE ASSAULT,...,AO,Adult Other,626,NaN,NaN,NaN,6500 SHOUP AV,NaN,34.1885,-118.6190
39766,221209573,04/08/2022 12:00:00 AM,04/08/2022 12:00:00 AM,750,12,77th Street,1213,1,236,INTIMATE PARTNER - AGGRAVATED ASSAULT,...,IC,Invest Cont,236,NaN,NaN,NaN,5700 RUTHELEN ST,NaN,33.9910,-118.3126
39767,222007660,03/27/2022 12:00:00 AM,03/22/2022 12:00:00 AM,1645,20,Olympic,2022,2,901,VIOLATION OF RESTRAINING ORDER,...,IC,Invest Cont,901,NaN,NaN,NaN,300 S ST ANDREWS PL,NaN,34.0690,-118.3116
39768,222004129,01/04/2022 12:00:00 AM,01/02/2022 12:00:00 AM,2015,20,Olympic,2031,2,901,VIOLATION OF RESTRAINING ORDER,...,IC,Invest Cont,901,NaN,NaN,NaN,3900 W 7TH ST,NaN,34.0597,-118.3112
39769,220804602,01/16/2022 12:00:00 AM,01/16/2022 12:00:00 AM,1100,8,West LA,852,2,626,INTIMATE PARTNER - SIMPLE ASSAULT,...,IC,Invest Cont,626,NaN,NaN,NaN,1600 FEDERAL AV,NaN,34.0413,-118.4561

In [10]:
len(domestic_violence_df)

39770

In [11]:
domestic_violence_df.sort_values("dateocc", ascending=True).head(10)

,dr_no,daterptd,dateocc,timeocc,area,areaname,rptdistno,part1-2,crmcd,crmcddesc,...,status,statusdesc,crmcd1,crmcd2,crmcd3,crmcd4,location,crossstreet,lat,lon
204,200504050,01/01/2020 12:00:00 AM,01/01/2020 12:00:00 AM,1730,5,Harbor,515,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),...,AO,Adult Other,745,NaN,NaN,NaN,1600 N AVALON BL,NaN,33.7948,-118.2694
201,200504010,01/01/2020 12:00:00 AM,01/01/2020 12:00:00 AM,2100,5,Harbor,526,1,350,"THEFT, PERSON",...,AA,Adult Arrest,350,NaN,NaN,NaN,G,ISLAND,33.7783,-118.2662
202,200504021,01/01/2020 12:00:00 AM,01/01/2020 12:00:00 AM,1930,5,Harbor,558,2,626,INTIMATE PARTNER - SIMPLE ASSAULT,...,AA,Adult Arrest,626,NaN,NaN,NaN,100 W SANTA CRUZ ST,NaN,33.7442,-118.2796
203,200504032,01/01/2020 12:00:00 AM,01/01/2020 12:00:00 AM,400,5,Harbor,531,2,626,INTIMATE PARTNER - SIMPLE ASSAULT,...,IC,Invest Cont,626,NaN,NaN,NaN,1600 W 260TH ST,NaN,33.7869,-118.3043
9616,201205964,01/28/2020 12:00:00 AM,01/01/2020 12:00:00 AM,15,12,77th Street,1259,2,626,INTIMATE PARTNER - SIMPLE ASSAULT,...,IC,Invest Cont,626,NaN,NaN,NaN,78TH ST,CENTRAL AV,33.9685,-118.2564
6402,200604004,01/01/2020 12:00:00 AM,01/01/2020 12:00:00 AM,10,6,Hollywood,668,2,626,INTIMATE PARTNER - SIMPLE ASSAULT,...,AA,Adult Arrest,626,NaN,NaN,NaN,5700 VIRGINIA AV,NaN,34.0918,-118.3136
1114,200104006,01/01/2020 12:00:00 AM,01/01/2020 12:00:00 AM,30,1,Central,101,2,626,INTIMATE PARTNER - SIMPLE ASSAULT,...,AO,Adult Other,626,NaN,NaN,NaN,900 FIGUEROA TR,NaN,34.0663,-118.2441
6449,200704041,01/01/2020 12:00:00 AM,01/01/2020 12:00:00 AM,1210,7,Wilshire,724,1,236,INTIMATE PARTNER - AGGRAVATED ASSAULT,...,IC,Invest Cont,236,NaN,NaN,NaN,100 S GARDNER ST,NaN,34.0735,-118.3571
10533,201804046,01/01/2020 12:00:00 AM,01/01/2020 12:00:00 AM,1215,18,Southeast,1844,1,236,INTIMATE PARTNER - AGGRAVATED ASSAULT,...,AO,Adult Other,236,NaN,NaN,NaN,900 E 112TH ST,NaN,33.9328,-118.2556
12592,201804020,01/01/2020 12:00:00 AM,01/01/2020 12:00:00 AM,300,18,Southeast,1806,1,350,"THEFT, PERSON",...,IC,Invest Cont,350,626.0,NaN,NaN,9100 STANFORD AV,NaN,33.9534,-118.2630

In [12]:
domestic_violence_df.value_counts("areaname")

areaname
77th Street    3867
Southeast      3407
Southwest      3126
Rampart        2343
Harbor         2339
Newton         2116
Mission        2108
Olympic        2092
West Valley    1816
Central        1774
N Hollywood    1728
Hollywood      1642
Topanga        1617
Devonshire     1597
Van Nuys       1504
Hollenbeck     1472
Foothill       1323
Pacific        1234
Northeast      1014
Wilshire        991
West LA         660
dtype: int64

In [13]:
domestic_violence_df.value_counts("crmcddesc")

crmcddesc
INTIMATE PARTNER - SIMPLE ASSAULT            23834
INTIMATE PARTNER - AGGRAVATED ASSAULT         6671
CRIMINAL THREATS - NO WEAPON DISPLAYED        1263
VIOLATION OF RESTRAINING ORDER                1229
BRANDISH WEAPON                                735
                                             ...
CHILD PORNOGRAPHY                                1
SHOPLIFTING - PETTY THEFT ($950 & UNDER)         1
SEX OFFENDER REGISTRANT OUT OF COMPLIANCE        1
CONTRIBUTING                                     1
CONSPIRACY                                       1
Length: 74, dtype: int64

In [14]:
domestic_violence_df[domestic_violence_df["areaname"] == "77th Street"]

,dr_no,daterptd,dateocc,timeocc,area,areaname,rptdistno,part1-2,crmcd,crmcddesc,...,status,statusdesc,crmcd1,crmcd2,crmcd3,crmcd4,location,crossstreet,lat,lon
2844,200317623,09/20/2020 12:00:00 AM,09/20/2020 12:00:00 AM,1355,12,77th Street,1203,1,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),...,AO,Adult Other,420,NaN,NaN,NaN,4400 S WESTERN AV,NaN,34.0033,-118.3089
7613,201217850,08/04/2020 12:00:00 AM,08/04/2020 12:00:00 AM,1000,12,77th Street,1249,2,626,INTIMATE PARTNER - SIMPLE ASSAULT,...,AO,Adult Other,626,NaN,NaN,NaN,6700 S FIGUEROA ST,NaN,33.9786,-118.2827
7614,201222029,10/04/2020 12:00:00 AM,10/04/2020 12:00:00 AM,1800,12,77th Street,1268,2,626,INTIMATE PARTNER - SIMPLE ASSAULT,...,IC,Invest Cont,626,NaN,NaN,NaN,100 E 84TH PL,NaN,33.9619,-118.2717
7617,201207213,02/05/2020 12:00:00 AM,02/05/2020 12:00:00 AM,800,12,77th Street,1241,2,626,INTIMATE PARTNER - SIMPLE ASSAULT,...,IC,Invest Cont,626,NaN,NaN,NaN,6400 11TH AV,NaN,33.9817,-118.3294
7626,201218195,08/09/2020 12:00:00 AM,08/09/2020 12:00:00 AM,200,12,77th Street,1256,1,236,INTIMATE PARTNER - AGGRAVATED ASSAULT,...,AA,Adult Arrest,236,NaN,NaN,NaN,700 W 74TH ST,NaN,33.9727,-118.2846
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39653,221208626,03/23/2022 12:00:00 AM,03/23/2022 12:00:00 AM,1220,12,77th Street,1215,1,236,INTIMATE PARTNER - AGGRAVATED ASSAULT,...,IC,Invest Cont,236,NaN,NaN,NaN,SLAUSON AV,VERMONT AV,33.9891,-118.2915
39681,221210488,04/22/2022 12:00:00 AM,04/21/2022 12:00:00 AM,2130,12,77th Street,1235,2,626,INTIMATE PARTNER - SIMPLE ASSAULT,...,IC,Invest Cont,626,NaN,NaN,NaN,1300 W 58TH PL,NaN,33.9883,-118.2980
39706,221206704,02/20/2022 12:00:00 AM,02/20/2022 12:00:00 AM,1000,12,77th Street,1268,2,626,INTIMATE PARTNER - SIMPLE ASSAULT,...,IC,Invest Cont,626,NaN,NaN,NaN,8200 S MAIN ST,NaN,33.9654,-118.2739
39718,221205221,01/24/2022 12:00:00 AM,01/24/2022 12:00:00 AM,2350,12,77th Street,1208,2,626,INTIMATE PARTNER - SIMPLE ASSAULT,...,IC,Invest Cont,626,NaN,NaN,NaN,700 W 51ST ST,NaN,33.9964,-118.2860
39766,221209573,04/08/2022 12:00:00 AM,04/08/2022 12:00:00 AM,750,12,77th Street,1213,1,236,INTIMATE PARTNER - AGGRAVATED ASSAULT,...,IC,Invest Cont,236,NaN,NaN,NaN,5700 RUTHELEN ST,NaN,33.9910,-118.3126

In [15]:
district77street = (
    domestic_violence_df[domestic_violence_df["areaname"] == "77th Street"]["rptdistno"]
    .value_counts()
    .index
)

In [16]:
crime_df = pd.read_csv("Crime_Data.csv")

In [17]:
crime_df.columns = crime_df.columns.str.lower().str.replace(" ", "", regex=False)

In [18]:
crime_df.head()

,dr_no,daterptd,dateocc,timeocc,area,areaname,rptdistno,part1-2,crmcd,crmcddesc,...,status,statusdesc,crmcd1,crmcd2,crmcd3,crmcd4,location,crossstreet,lat,lon
0,10304468,01/08/2020 12:00:00 AM,01/08/2020 12:00:00 AM,2230,3,Southwest,377,2,624,BATTERY - SIMPLE ASSAULT,...,AO,Adult Other,624.0,NaN,NaN,NaN,1100 W 39TH PL,NaN,34.0141,-118.2978
1,190101086,01/02/2020 12:00:00 AM,01/01/2020 12:00:00 AM,330,1,Central,163,2,624,BATTERY - SIMPLE ASSAULT,...,IC,Invest Cont,624.0,NaN,NaN,NaN,700 S HILL ST,NaN,34.0459,-118.2545
2,191501505,01/01/2020 12:00:00 AM,01/01/2020 12:00:00 AM,1730,15,N Hollywood,1543,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),...,IC,Invest Cont,745.0,998.0,NaN,NaN,5400 CORTEEN PL,NaN,34.1685,-118.4019
3,191921269,01/01/2020 12:00:00 AM,01/01/2020 12:00:00 AM,415,19,Mission,1998,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,IC,Invest Cont,740.0,NaN,NaN,NaN,14400 TITUS ST,NaN,34.2198,-118.4468
4,200100501,01/02/2020 12:00:00 AM,01/01/2020 12:00:00 AM,30,1,Central,163,1,121,"RAPE, FORCIBLE",...,IC,Invest Cont,121.0,998.0,NaN,NaN,700 S BROADWAY,NaN,34.0452,-118.2534

In [19]:
crime_df.tail()

,dr_no,daterptd,dateocc,timeocc,area,areaname,rptdistno,part1-2,crmcd,crmcddesc,...,status,statusdesc,crmcd1,crmcd2,crmcd3,crmcd4,location,crossstreet,lat,lon
476961,221906145,02/23/2022 12:00:00 AM,02/23/2022 12:00:00 AM,1210,19,Mission,1985,1,421,THEFT FROM MOTOR VEHICLE - ATTEMPT,...,IC,Invest Cont,421.0,998.0,NaN,NaN,8400 VAN NUYS BL,NaN,34.2229,-118.4487
476962,221108224,04/23/2022 12:00:00 AM,04/23/2022 12:00:00 AM,100,11,Northeast,1189,1,210,ROBBERY,...,IC,Invest Cont,210.0,NaN,NaN,NaN,3200 N FIGUEROA ST,NaN,34.0854,-118.2204
476963,221005507,02/10/2022 12:00:00 AM,02/09/2022 12:00:00 AM,1530,10,West Valley,1024,1,510,VEHICLE - STOLEN,...,IC,Invest Cont,510.0,NaN,NaN,NaN,18800 SHERMAN WY,NaN,34.2011,-118.5426
476964,221105477,02/10/2022 12:00:00 AM,02/08/2022 12:00:00 AM,2000,11,Northeast,1171,1,510,VEHICLE - STOLEN,...,IC,Invest Cont,510.0,NaN,NaN,NaN,4000 FOUNTAIN AV,NaN,34.0958,-118.2787
476965,221605448,02/15/2022 12:00:00 AM,02/14/2022 12:00:00 AM,1800,16,Foothill,1613,1,331,THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND ...,...,IC,Invest Cont,331.0,NaN,NaN,NaN,12700 VAN NUYS BL,NaN,34.2755,-118.4092

In [20]:
crime_df.value_counts("areaname")

areaname
77th Street    30397
Central        29882
Pacific        28472
Southwest      26310
Hollywood      25983
Southeast      24510
N Hollywood    24282
Olympic        24074
Newton         23328
West LA        22253
Wilshire       22224
Rampart        21885
Northeast      20766
Harbor         20496
Van Nuys       20189
Mission        19556
West Valley    19504
Topanga        19282
Devonshire     18920
Hollenbeck     18287
Foothill       16366
dtype: int64

In [21]:
crime_df.value_counts("crmcddesc")

crmcddesc
VEHICLE - STOLEN                                           52603
BATTERY - SIMPLE ASSAULT                                   38119
BURGLARY FROM VEHICLE                                      30980
VANDALISM - FELONY ($400 & OVER, ALL CHURCH VANDALISMS)    30857
BURGLARY                                                   29347
                                                           ...
FIREARMS RESTRAINING ORDER (FIREARMS RO)                       3
TELEPHONE PROPERTY - DAMAGE                                    2
FIREARMS EMERGENCY PROTECTIVE ORDER (FIREARMS EPO)             2
FAILURE TO DISPERSE                                            2
GRAND THEFT / AUTO REPAIR                                      1
Length: 135, dtype: int64

In [22]:
domestic_violence_df["crmcddesc"]

0            INTIMATE PARTNER - SIMPLE ASSAULT
1            INTIMATE PARTNER - SIMPLE ASSAULT
2            INTIMATE PARTNER - SIMPLE ASSAULT
3            INTIMATE PARTNER - SIMPLE ASSAULT
4            INTIMATE PARTNER - SIMPLE ASSAULT
                         ...
39765        INTIMATE PARTNER - SIMPLE ASSAULT
39766    INTIMATE PARTNER - AGGRAVATED ASSAULT
39767           VIOLATION OF RESTRAINING ORDER
39768           VIOLATION OF RESTRAINING ORDER
39769        INTIMATE PARTNER - SIMPLE ASSAULT
Name: crmcddesc, Length: 39770, dtype: object

In [23]:
domestic_violence_df["areaname"]

0         Hollenbeck
1            Central
2            Central
3            Central
4            Central
            ...
39765        Topanga
39766    77th Street
39767        Olympic
39768        Olympic
39769        West LA
Name: areaname, Length: 39770, dtype: object

In [24]:
crime_df["crmcddesc"]

0                                  BATTERY - SIMPLE ASSAULT
1                                  BATTERY - SIMPLE ASSAULT
2                  VANDALISM - MISDEAMEANOR ($399 OR UNDER)
3         VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...
4                                            RAPE, FORCIBLE
                                ...
476961                   THEFT FROM MOTOR VEHICLE - ATTEMPT
476962                                              ROBBERY
476963                                     VEHICLE - STOLEN
476964                                     VEHICLE - STOLEN
476965    THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND ...
Name: crmcddesc, Length: 476966, dtype: object

In [25]:
crime_df["areaname"]

0           Southwest
1             Central
2         N Hollywood
3             Mission
4             Central
             ...
476961        Mission
476962      Northeast
476963    West Valley
476964      Northeast
476965       Foothill
Name: areaname, Length: 476966, dtype: object

In [26]:
typeofviolence = domestic_violence_df.groupby("crmcddesc")

In [27]:
typeofviolence.first()

,dr_no,daterptd,dateocc,timeocc,area,areaname,rptdistno,part1-2,crmcd,mocodes,...,status,statusdesc,crmcd1,crmcd2,crmcd3,crmcd4,location,crossstreet,lat,lon
crmcddesc,,,,,,,,,,,,,,,,,,,,,
ARSON,200210897,06/02/2020 12:00:00 AM,06/02/2020 12:00:00 AM,1500,2,Rampart,201,1,648,1402 1813 0913 0421 0334 1309 2000,...,AA,Adult Arrest,648,998.0,NaN,NaN,1000 N HELIOTROPE DR,VENICE,34.0894,-118.2950
"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",200400543,01/20/2020 12:00:00 AM,01/19/2020 12:00:00 AM,1330,4,Hollenbeck,453,1,230,1402 1407 1419 0913 1814 2000 0400 0411,...,AA,Adult Arrest,230,998.0,745.0,NaN,200 ECHANDIA ST,LOS ANGELES ST,34.0494,-118.2204
ATTEMPTED ROBBERY,200505191,01/29/2020 12:00:00 AM,01/29/2020 12:00:00 AM,630,5,Harbor,561,1,220,2004 2000 1814 0448 1309 0913 0340 0421 0408,...,AA,Adult Arrest,220,626.0,NaN,NaN,1400 W 9TH ST,MIRAMAR,33.7361,-118.3077
BATTERY - SIMPLE ASSAULT,200404735,01/20/2020 12:00:00 AM,01/19/2020 12:00:00 AM,2030,4,Hollenbeck,437,2,624,0400 0416 0913 1813 2000,...,IC,Invest Cont,624,998.0,NaN,NaN,1800 DEL PASO AV,BONNIE BRAE,34.0632,-118.1821
BATTERY POLICE (SIMPLE),200121428,11/23/2020 12:00:00 AM,11/23/2020 12:00:00 AM,210,1,Central,111,2,623,2000 1601 2004 1218 0444 0429,...,AA,Adult Arrest,623,NaN,NaN,NaN,500 N LOS ANGELES ST,None,34.0560,-118.2386
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
VANDALISM - MISDEAMEANOR ($399 OR UNDER),200304269,01/04/2020 12:00:00 AM,01/04/2020 12:00:00 AM,2040,3,Southwest,354,2,745,0329 2000 1814 0321 2002,...,AO,Adult Other,745,998.0,NaN,NaN,3700 3RD AV,JEFFERSON BL,34.0203,-118.3201
VEHICLE - STOLEN,200611650,06/22/2020 12:00:00 AM,06/22/2020 12:00:00 AM,1415,6,Hollywood,647,1,510,2000 1813 1814 0913 1300 1309 1310 0400 0448 0344,...,IC,Invest Cont,510,626.0,NaN,NaN,HOLLYWOOD,ARGYLE,34.1016,-118.3252
VIOLATION OF COURT ORDER,200105449,01/20/2020 12:00:00 AM,01/20/2020 12:00:00 AM,1925,1,Central,157,2,900,2038 2000 0913 1906 1813,...,IC,Invest Cont,900,998.0,NaN,NaN,500 S SAN PEDRO ST,ARLINGTON,34.0442,-118.2439
VIOLATION OF RESTRAINING ORDER,200304266,01/05/2020 12:00:00 AM,01/05/2020 12:00:00 AM,1920,3,Southwest,361,2,901,2000 1813 0329 2038,...,IC,Invest Cont,901,998.0,NaN,NaN,4000 STEVELY AV,2ND AV,34.0150,-118.3536
VIOLATION OF TEMPORARY RESTRAINING ORDER,200306290,02/08/2020 12:00:00 AM,02/08/2020 12:00:00 AM,852,3,Southwest,363,2,902,2038 2000 1814 1906,...,AA,Adult Arrest,902,998.0,NaN,NaN,MUIRFIELD RD,SANTO TOMAS DR,34.0111,-118.3477

In [28]:
typeofviolence.max()

/var/folders/d6/smrm7b4d70z7d6cd7r2398fh0000gn/T/ipykernel_11817/2263216651.py:1: FutureWarning: Dropping invalid columns in DataFrameGroupBy.max is deprecated. In a future version, a TypeError will be raised. Before calling .max, select only columns which should be valid for the function.
  typeofviolence.max()

,dr_no,daterptd,dateocc,timeocc,area,areaname,rptdistno,part1-2,crmcd,mocodes,...,weaponusedcd,status,statusdesc,crmcd1,crmcd2,crmcd3,crmcd4,location,lat,lon
crmcddesc,,,,,,,,,,,,,,,,,,,,,
ARSON,222105532,12/27/2020 12:00:00 AM,12/27/2020 12:00:00 AM,2300,21,Topanga,438,1,648,2000 1814 0913 0444 1501,...,506.0,IC,Invest Cont,648,998.0,NaN,NaN,GLOBE,34.1660,0.0000
"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",222106694,12/31/2020 12:00:00 AM,12/31/2021 12:00:00 AM,2350,21,Wilshire,935,1,230,2060 2000 1218 1402 2004 1813 0913 0334 0445 1414,...,513.0,IC,Invest Cont,230,998.0,998.0,NaN,YOSEMITE,34.3274,-118.1623
ATTEMPTED ROBBERY,221204545,12/19/2021 12:00:00 AM,12/19/2021 12:00:00 AM,2310,21,Wilshire,906,1,220,2004 2000 1814 0448 1309 0913 0340 0421 0408,...,500.0,IC,Invest Cont,220,998.0,NaN,NaN,WESTMORELAND AV,34.3048,-118.1906
BATTERY - SIMPLE ASSAULT,222100563,12/29/2021 12:00:00 AM,12/31/2021 12:00:00 AM,2359,21,Wilshire,991,2,624,2038 0416 0446 2000 1814,...,515.0,IC,Invest Cont,624,998.0,NaN,NaN,YOLANDA,34.3202,0.0000
BATTERY POLICE (SIMPLE),200121428,11/23/2020 12:00:00 AM,11/23/2020 12:00:00 AM,210,1,Central,111,2,623,2000 1601 2004 1218 0444 0429,...,400.0,AA,Adult Arrest,623,NaN,NaN,NaN,500 N LOS ANGELES ST,34.0560,-118.2386
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
VANDALISM - MISDEAMEANOR ($399 OR UNDER),222105298,12/31/2020 12:00:00 AM,12/31/2020 12:00:00 AM,2350,21,Wilshire,998,2,745,2038 0913 1821 2000 1300 0329,...,511.0,IC,Invest Cont,745,999.0,NaN,NaN,WOODMAN,34.3244,-118.1769
VEHICLE - STOLEN,201818728,10/13/2020 12:00:00 AM,10/13/2020 12:00:00 AM,1415,18,Southeast,647,1,510,2000 1814 0354 1300 1309 0416,...,400.0,IC,Invest Cont,510,626.0,NaN,NaN,HOLLYWOOD,34.1016,-118.2784
VIOLATION OF COURT ORDER,222108153,12/31/2021 12:00:00 AM,12/31/2021 12:00:00 AM,2356,21,Wilshire,985,2,900,2039 0913 1814 2000 1210,...,515.0,IC,Invest Cont,900,998.0,NaN,NaN,WYANDOTTE ST,34.3187,0.0000
VIOLATION OF RESTRAINING ORDER,222108008,12/31/2020 12:00:00 AM,12/31/2020 12:00:00 AM,2359,21,Wilshire,994,2,901,2038 2041 2000 1814 0913,...,515.0,IC,Invest Cont,901,999.0,NaN,NaN,WOODMAN AV,34.3235,0.0000
VIOLATION OF TEMPORARY RESTRAINING ORDER,222107234,12/27/2021 12:00:00 AM,12/27/2021 12:00:00 AM,2345,21,Wilshire,952,2,902,2038 2021 1202 2000 1813,...,515.0,IC,Invest Cont,902,998.0,NaN,NaN,TRINITY ST,34.2878,0.0000

In [29]:
print(domestic_violence_df.columns.tolist())

['dr_no', 'daterptd', 'dateocc', 'timeocc', 'area', 'areaname', 'rptdistno', 'part1-2', 'crmcd', 'crmcddesc', 'mocodes', 'victage', 'victsex', 'victdescent', 'premiscd', 'premisdesc', 'weaponusedcd', 'weapondesc', 'status', 'statusdesc', 'crmcd1', 'crmcd2', 'crmcd3', 'crmcd4', 'location', 'crossstreet', 'lat', 'lon']

In [30]:
domestic_violence_df.describe()

,dr_no,timeocc,area,part1-2,crmcd,victage,premiscd,weaponusedcd,crmcd1,crmcd2,crmcd3,crmcd4,lat,lon
count,3.977000e+04,39770.000000,39770.000000,39770.000000,39770.000000,39770.000000,39770.000000,35891.000000,39770.000000,3512.000000,194.000000,11.0,39770.000000,39770.000000
mean,2.082996e+08,1318.281519,11.087252,1.744129,572.185693,34.422278,395.875006,392.332451,571.182474,889.621583,961.896907,998.0,33.839042,-117.567541
std,6.966246e+06,720.587590,6.280375,0.436355,203.891605,12.047757,179.284125,69.814049,203.337416,172.019797,81.664610,0.0,2.758471,9.574724
min,1.901011e+08,1.000000,1.000000,1.000000,110.000000,0.000000,101.000000,101.000000,110.000000,230.000000,626.000000,998.0,0.000000,-118.667200
25%,2.013145e+08,800.000000,5.000000,1.000000,626.000000,26.000000,122.000000,400.000000,626.000000,761.000000,998.000000,998.0,33.989100,-118.418100
50%,2.103200e+08,1405.000000,12.000000,2.000000,626.000000,32.000000,501.000000,400.000000,626.000000,998.000000,998.000000,998.0,34.049800,-118.305850
75%,2.117068e+08,1950.000000,17.000000,2.000000,626.000000,41.000000,502.000000,400.000000,626.000000,998.000000,998.000000,998.0,34.172300,-118.273900
max,2.221086e+08,2359.000000,21.000000,2.000000,956.000000,99.000000,971.000000,515.000000,956.000000,999.000000,998.000000,998.0,34.333000,0.000000

In [31]:
crime_df.describe()

,dr_no,timeocc,area,rptdistno,part1-2,crmcd,victage,premiscd,weaponusedcd,crmcd1,crmcd2,crmcd3,crmcd4,lat,lon
count,4.769660e+05,476966.000000,476966.000000,476966.000000,476966.000000,476966.000000,476966.000000,476961.000000,170373.000000,476961.000000,37232.000000,1272.000000,36.000000,476966.000000,476966.000000
mean,2.086846e+08,1346.908484,10.768849,1123.163410,1.411252,505.079840,29.952183,298.936766,361.292376,504.808326,955.268130,981.979560,987.333333,33.910683,-117.789486
std,7.145784e+06,652.128236,6.065618,606.625845,0.492061,209.261032,21.715861,215.536619,124.173094,209.052436,115.396922,55.400008,34.766979,2.351284,8.158664
min,8.170000e+02,1.000000,1.000000,101.000000,1.000000,110.000000,-1.000000,101.000000,101.000000,110.000000,210.000000,434.000000,821.000000,0.000000,-118.667600
25%,2.013189e+08,905.000000,6.000000,628.000000,1.000000,330.000000,11.000000,101.000000,308.000000,330.000000,998.000000,998.000000,998.000000,34.011000,-118.430100
50%,2.105119e+08,1430.000000,11.000000,1145.000000,1.000000,480.000000,31.000000,203.000000,400.000000,480.000000,998.000000,998.000000,998.000000,34.058300,-118.322300
75%,2.117096e+08,1900.000000,16.000000,1621.000000,2.000000,626.000000,45.000000,501.000000,400.000000,626.000000,998.000000,998.000000,998.000000,34.163100,-118.274000
max,2.299104e+08,2359.000000,21.000000,2199.000000,2.000000,956.000000,120.000000,971.000000,516.000000,956.000000,999.000000,999.000000,999.000000,34.334300,0.000000

In [32]:
districts = gpd.read_file("districtsLA.geojson")

In [33]:
district77street

Index(['1241', '1269', '1266', '1268', '1258', '1245', '1265', '1259', '1267',
       '1283', '1243', '1249', '1256', '1208', '1251', '1257', '1218', '1239',
       '1211', '1213', '1203', '1273', '1248', '1263', '1215', '1232', '1253',
       '1207', '1204', '1233', '1255', '1235', '1205', '1252', '1242', '1209',
       '1231', '1219', '1293'],
      dtype='object')

In [34]:
districts.head()

,name,rd,agency,label,omega_name,objectid,s_type,commtype,omega_label,shape_stlength,shape_starea,st_name,station,geometry
0,Pasadena,1425,OTHER,Pasadena Police,OTHER PASADENA 1425,3944,Police,City,Pasadena 1425,1371.7779692348784,79866.3291015625,Pasadena,None,"MULTIPOLYGON (((-118.06809 34.16417, -118.0682..."
1,Pasadena,107,OTHER,Pasadena Police,OTHER PASADENA 107,3517,Police,City,Pasadena 107,2531.2994481855621,127026.11328125,Pasadena,None,"MULTIPOLYGON (((-118.16683 34.15911, -118.1668..."
2,Whittier,77,OTHER,Whittier Police,OTHER WHITTIER 77,705,Police,City,Whittier 77,16506.377014295165,7262257.6474609375,Whittier,None,"MULTIPOLYGON (((-118.01532 33.98608, -118.0152..."
3,Monrovia,NW5,OTHER,Monrovia Police,OTHER MONROVIA NW5,680,Police,City,Monrovia NW5,13440.816213218595,9266201.5087890625,Monrovia,None,"MULTIPOLYGON (((-118.02046 34.15761, -118.0130..."
4,Hawaiian Gardens,1351,LASD,Lakewood Sheriff,LASD LAKEWOOD 1351,2679,Sheriff,City,LASD 1351,18342.947680042955,16256902.184570313,Lakewood,LAKEWOOD,"MULTIPOLYGON (((-118.06329 33.82416, -118.0638..."

In [35]:
districts[districts["rd"].isin(district77street)]

,name,rd,agency,label,omega_name,objectid,s_type,commtype,omega_label,shape_stlength,shape_starea,st_name,station,geometry
34,Pasadena,1215,OTHER,Pasadena Police,OTHER PASADENA 1215,3783,Police,City,Pasadena 1215,2218.7613788079784,258924.8876953125,Pasadena,None,"MULTIPOLYGON (((-118.09611 34.14797, -118.0961..."
168,Pasadena,1241,OTHER,Pasadena Police,OTHER PASADENA 1241,3812,Police,City,Pasadena 1241,3146.5167004925966,295564.0947265625,Pasadena,None,"MULTIPOLYGON (((-118.09463 34.14213, -118.0946..."
174,Los Angeles,1241,LAPD,LAPD 77th Street Division,LAPD 77TH STREET 1241,1907,LAPD,City,LAPD 1241,12599.960487352666,8380701.6787109375,77th Street Division,77TH STREET,"MULTIPOLYGON (((-118.32649 33.98186, -118.3265..."
197,Los Angeles,1249,LAPD,LAPD 77th Street Division,LAPD 77TH STREET 1249,1912,LAPD,City,LAPD 1249,10159.56900091225,5989041.3037109375,77th Street Division,77TH STREET,"MULTIPOLYGON (((-118.28052 33.98329, -118.2805..."
317,Los Angeles,1239,LAPD,LAPD 77th Street Division,LAPD 77TH STREET 1239,1906,LAPD,City,LAPD 1239,13919.025707897817,9751357.7275390625,77th Street Division,77TH STREET,"MULTIPOLYGON (((-118.28052 33.98329, -118.2811..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5197,Los Angeles,1242,LAPD,LAPD 77th Street Division,LAPD 77TH STREET 1242,1908,LAPD,City,LAPD 1242,10613.293822333422,7039980.068359375,77th Street Division,77TH STREET,"MULTIPOLYGON (((-118.31766 33.98336, -118.3177..."
5202,Los Angeles,1231,LAPD,LAPD 77th Street Division,LAPD 77TH STREET 1231,1902,LAPD,City,LAPD 1231,18193.877715213181,12726183.647460938,77th Street Division,77TH STREET,"MULTIPOLYGON (((-118.34956 33.98938, -118.3493..."
5256,Angeles National Forest,1259,LASD,Crescenta Valley Sheriff,LASD CRESCENTA VALLEY 1259,2653,Sheriff,Unincorporated,LASD 1259,341109.92878381768,2605150286.1728516,Crescenta Valley,CRESCENTA VALLEY,"MULTIPOLYGON (((-118.08136 34.39157, -118.0811..."
5258,Los Angeles,1257,LAPD,LAPD 77th Street Division,LAPD 77TH STREET 1257,1918,LAPD,City,LAPD 1257,10226.429734965643,4287695.421875,77th Street Division,77TH STREET,"MULTIPOLYGON (((-118.27830 33.96790, -118.2789..."
5292,Los Angeles,1259,LAPD,LAPD 77th Street Division,LAPD 77TH STREET 1259,1920,LAPD,City,LAPD 1259,13370.612115188629,10699509.5390625,77th Street Division,77TH STREET,"MULTIPOLYGON (((-118.25628 33.97478, -118.2562..."

In [36]:
districts.dtypes

name                object
rd                  object
agency              object
label               object
omega_name          object
objectid            object
s_type              object
commtype            object
omega_label         object
shape_stlength      object
shape_starea        object
st_name             object
station             object
geometry          geometry
dtype: object

In [37]:
pruneddistricts = districts[districts["rd"].isin(district77street)]

In [38]:
pruneddistricts.to_file("pruneddistricts.geojson", driver="GeoJSON")

In [39]:
southeastdistrictnumbers = (
    domestic_violence_df[domestic_violence_df["areaname"] == "Southeast"]["rptdistno"]
    .value_counts()
    .index
)

In [40]:
southeastdistrictnumbers

Index(['1822', '1842', '1801', '1802', '1846', '1844', '1821', '1824', '1823',
       '1849', '1826', '1837', '1827', '1841', '1862', '1861', '1804', '1832',
       '1834', '1863', '1831', '1836', '1829', '1806', '1881', '1864', '1838',
       '1871', '1891', '1805', '1839', '1803', '1851', '1835'],
      dtype='object')

In [41]:
pruneddistricts = districts[districts["rd"].isin(southeastdistrictnumbers)]

In [42]:
pruneddistricts.to_file("southeastdistricts.geojson", driver="GeoJSON")

In [44]:
domestic_violence_df.value_counts.()

dr_no      daterptd                dateocc                 timeocc  area  areaname   rptdistno  part1-2  crmcd  crmcddesc        mocodes                                            victage  victsex  victdescent  premiscd  premisdesc   weaponusedcd  weapondesc  status  statusdesc   crmcd1  crmcd2  crmcd3  crmcd4  location  crossstreet  lat      lon
200613424  08/02/2020 12:00:00 AM  08/02/2020 12:00:00 AM  2030     6     Hollywood  657        1        761    BRANDISH WEAPON  1402 2000 1813 1814 0400 0416 0448 0329 0913 0421  34       F        H            108       PARKING LOT  212.0         BOTTLE      AO      Adult Other  761     920.0   930.0   998.0   WESTERN   ROMAINE      34.0885  -118.3092    1
dtype: int64